### ISSUE TITLE
Add functionality to delete names from the Player Name field

### ISSUE THREAD

**Issue by RobThePM** [cheshire137/overwatch-team-comps#84] opened 2017-03-18 18:48 UTC
As I type in player names (or add them via BattleNet), the names are saved the next time I go to type in another player name. This could lead to a long list. It would be nice to have a way to delete them.

**Comment by cheshire137** [comment] 2017-03-18 19:19
Yep, we definitely need this! Closing this as a dupe of #67 though. ❤️

**Closed by cheshire137** 2017-03-18 19:19 UTC
